sudo: required
dist: trusty
language: java
jdk:
  #- openjdk7 # disable until https://github.com/travis-ci/travis-ci/issues/5227 is fixed
  - oraclejdk7
  - oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_script:
  # Show OS
  - cat /etc/os-release
  - python3 --version
  # Libsodium
  - sudo add-apt-repository -y ppa:chris-lea/libsodium
  - sudo apt-get update && sudo apt-get install -y libsodium-dev
  # Create test certificate for localhost
  - openssl req -new -newkey rsa:1024 -nodes -sha256 -out saltyrtc.csr -keyout saltyrtc.key -subj '/C=CH/O=SaltyRTC/CN=localhost/'
  - openssl x509 -req -days 365 -in saltyrtc.csr -signkey saltyrtc.key -out saltyrtc.crt
  - keytool -import -trustcacerts -alias root -file saltyrtc.crt -keystore saltyrtc.jks -storetype JKS -storepass saltyrtc -noprompt
  # Start SaltyRTC server
  - git clone https://github.com/saltyrtc/saltyrtc-server-python -b master
  - export SALTYRTC_SERVER_PERMANENT_KEY=0919b266ce1855419e4066fc076b39855e728768e3afa773105edd2e37037c20
  - |
    cd saltyrtc-server-python
    pyvenv venv
    venv/bin/pip install .[logging]
    venv/bin/saltyrtc-server -v 5 serve -sc ../saltyrtc.crt -sk ../saltyrtc.key -p 8765 -k $SALTYRTC_SERVER_PERMANENT_KEY > serverlog.txt 2>&1 &
    export SALTYRTC_SERVER_PID=$!
    sleep 2
    cd ..
  # Enable debug in integration tests
  - sed -i 's/DEBUG = false/DEBUG = true/' src/test/java/org/saltyrtc/client/tests/integration/ConnectionTest.java
after_script:
  # Stop SaltyRTC server
  - kill -INT $SALTYRTC_SERVER_PID
  # Print server log
  - |
    echo "---------- Server Log ----------\n"
    cat saltyrtc-server-python/serverlog.txt
    echo -e "\n---------- End Server Log ----------"
