site_name: SaltyRTC Client for Java
site_description: Documentation for saltyrtc-client-java.
site_author: Threema GmbH
copyright: © 2016-2017 Threema GmbH
theme: readthedocs
repo_url: https://github.com/saltyrtc/saltyrtc-client-java
edit_uri: edit/master/docs/docs/
markdown_extensions:
  - smarty
  - toc:
      permalink: False
pages:
  - Home: index.md
  - Guide:
    - Installing: installing.md
    - Usage: usage.md
    - Reference: reference.md
  - About: about.md
